services:
  front:
    image: trafex/php-nginx
    # trestart: always
    volumes:
      - ./dist:/var/www/html
    ports:
      - "8000:8080"
    depends_on:
      - json-server

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    volumes:
      - .:/data
    ports:
      - "3000:3000"
    # restart: always
