version: "3.8"

services:
  proxy:
    image: trafex/php-nginx
    # trestart: always
    volumes:
      - ./dist:/var/www/html
    ports:
      - "8001:8080"

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    ports:
      - "3000:3000"
    volumes:
      - ./:/data
    # restart: always
